### ISSUE TITLE
SyntaxError: Unexpected token i

### ISSUE THREAD

**Issue by 0x1ad2** [lesshint/gulp-lesshint#1] opened 2015-09-16 12:43 UTC
Hi Jonathan,

I tried to install the gulp plugin using NPM and your code example (changed the path and stripped the options).

``` javascript
gulp.task('lint', function() {
    return gulp.src('less/*.less')
        .pipe(lesshint())
});
```

But when I run it as a task or as a watcher it will throw the following error:
![error](https://i.gyazo.com/9a29a2f6d9e64ba73555aaed7860b3cb.png)

did I forget something?

**Comment by jwilsson** [comment] 2015-09-16 13:16
Hi,
Is that your full `gulpfile.js` or can you post everything? Could you also post the full output from Gulp?

Thanks!

**Comment by 0x1ad2** [comment] 2015-09-16 15:57
No that's not my full Gulp file also the output contains directories that might not be shared so I'll create a new screen cap containing everything and blurring out the dirs (I'll do it twommorow).

Over the weekend I wrote a blog on how to enhance your workflow with Gulp (you should read it: https://medium.com/@0x1AD2/how-to-enhance-your-front-end-development-workflow-using-gulp-cad48ee03552) so I can assume I know what I'm doing 😋

**Comment by 0x1ad2** [comment] 2015-09-18 07:37
I´ve tried to apply the task to one file only, I gives me a different error which is good but it's still an error.

``` javascript
/*
 * 0x1ad2 base Gulp.js file
 * https://twitter.com/0x1ad2
 */

/*
 * Define plugins
 */
var gulp = require('gulp');
var less = require('gulp-less');
var lesshint = require('gulp-lesshint');
var lesshintStylish = require('gulp-lesshint-stylish');


/*
 * Define paths
 */
var paths = {
    lessDirectory: 'less/'
};

/*
 * Define tasks
 */
gulp.task('lint', function() {
    return gulp.src(paths.lessDirectory+'style.less')
        .pipe(lesshint({
            // Options
        }))
});
```

![error](https://i.gyazo.com/ff94c1f679ca81161816e0393d3059be.png)

**Comment by jwilsson** [comment] 2015-09-18 13:10
Hmm, it looks like you to ran in to a [upstream issue](https://github.com/lesshint/lesshint/issues/62) related to our current naïve error handling. If possible, could you try with the latest code in the [`issue-62` branch](https://github.com/lesshint/lesshint/tree/issue-62) (`npm install lesshint/lesshint#issue-62` should do) and see what kind of error you're getting then?

Some stupid questions just to rule everything out:
Which version of `gulp-lesshint` are you running? I suppose it's the latest?
Could you double check your `.lesshintrc` just to make sure it's valid JSON?

**Comment by jwilsson** [comment] 2015-09-22 14:20
The `issue-62` branch has been merged into upstream `master`. `npm install lesshint/lesshint#master` should do instead.

**Comment by alferov** [comment] 2015-10-09 20:05
I'm having the same problem.
Code:

``` js
gulp.task('lint', function() {
  return gulp.src('./app/assets/less/*.less')
    .pipe(lesshint({
      // Options
    }));
});
```

But once I change it on:

``` js
  return gulp.src('./app/assets/less/main.less')
```

It works fine.
Could it be because of globes?

**Comment by alferov** [comment] 2015-10-09 20:22
I found the problem. One of the files contains the following line:

``` css
@import url(http://fonts.googleapis.com/css?family=Lato:400,300,700,900)
```

Once I removed it, linting was accomplished successfully.
@jwilsson, could you try to reproduce it? Thank you.

**Comment by jwilsson** [comment] 2015-10-10 08:29
@alferov thanks for this.

I managed to reproduce it and tracked it down to a upstream issue in [lesshint](https://github.com/lesshint/lesshint/). I'll post a new issue with more info there.

**Comment by jwilsson** [comment] 2015-10-10 08:56
@alferov I forgot to mention, you can bypass this for now by putting quotes around the URL.

**Comment by jwilsson** [comment] 2015-10-19 19:44
@0x1ad2 and @alferov could you try with the new `1.0` release which should give you better error messages. Just beware of some breaking changes, check the new example in the readme.

**Comment by alferov** [comment] 2015-10-20 20:28
@jwilsson, nice!
I just tried v `1.0` out and I can verify that the issue is fixed.

**Closed as completed** 2016-02-09 17:00 UTC
